### ISSUE TITLE
 Implement support for UDF array arguments

### ISSUE THREAD

**Issue by dharhas** [Quansight/omnisci#39]
Currently, UDFs support only scalar arguments, that is, UDFs are applied by row. Implement support for UDF array arguments, this task is dependent on availability of OmniSci staff to implement prerequisite functionality

**Comment by pearu** [comment]
Created https://github.com/omnisci/omniscidb-internal/pull/3726
Example of a UDF with array arguments:
https://github.com/xnd-project/rbc/blob/master/notebooks/rbc-omnisci-array.ipynb

**Comment by pearu** [comment]
Half-blocker: https://github.com/numba/numba/issues/4546 (has a temporary workaround).

**Comment by pearu** [comment]
In a sense, this issue is completed once the PR 3726 is merged. The merge is blocked by https://github.com/omnisci/omniscidb-internal/pull/3695 that needs to be merged first, then rebase and merge https://github.com/omnisci/omniscidb-internal/pull/3726 .

For sustainable support of UDF array arguments, https://github.com/numba/numba/issues/4546 needs to be resolved (estimated time: 40h)

For the next phase, I suggest implementing support for UDF geo arguments (estimated time: 40h)

**Comment by pearu** [comment]
Moved the numba issue to #69 and closing this one as complete.
